### ISSUE TITLE
No notification sounds

### ISSUE THREAD

**Issue by IvanikuV2** [ajbura/cinny#648]
### Describe the bug

When the "Notification Sound" option is enabled in settings you won't get any notification sounds when someone sends you a message

### Reproduction

1. Open settings
2. Go to Notifications
3. Enable Notification Sound
4. Wait for someone to send you a message

### Expected behavior

A notification sound should play

### Platform and versions

```shell
1. OS: Fedora Linux 16
2. Browser: Epiphany (WebKit GTK)
3. Cinny version: v2.0.4
4. Homeserver: irrelevant
```

**Comment by kfiven** [comment]
is it desktop app or cinny web you are using? @IvanikuV2

**Comment by kfiven** [comment]
oops misclick.

**Comment by IvanikuV2** [comment]
> is it desktop app or cinny web you are using? @IvanikuV2

As the issue says, I'm using Epiphany (GNOME Web browser) as a WebApp so yes, Web. But I also had this issue on the flatpak, strangely enough my friends also had this issue on their computers

**Comment by kfiven** [comment]
Is there any error in console? @IvanikuV2

**Comment by IvanikuV2** [comment]
Sorry for not being active in the issue, no, there doesn't seem to be any error or at least related to the notification sounds

**Comment by kfiven** [comment]
Weird, it's working fine here. Have you tried a different browser?

**Comment by IvanikuV2** [comment]
I'm using the one in gtk3-webview, I'll try Firefox when I get to my PC

**Comment by Abeehiltz** [comment]
I'm upping this ticket because I have the same issue on the **desktop** application. 
The sound notification works in the browser (Firefox). It's just the desktop application that doesn't work for me, on both my computers.

```
1. OS: MacOS Monterey 12.6 and Windows 11 version 22H2
2. Cinny version: v2.2.2
3. Homeserver: irrelevant (notifications work on Element)
```
### Console output
![image](https://user-images.githubusercontent.com/36138393/197345895-d9567dbf-11c1-4a78-96b2-621e369b3759.png)

No errors or warning, but in case some of the log can help you!

**Comment by kfiven** [comment]
Yeah in the case of desktop app this is known issue but issues for that are tracked at https://github.com/cinnyapp/cinny-desktop/issues
The OP seems to have it on the web app which I am not able to repro.

**Comment by ajbura** [comment]
https://github.com/matrix-org/matrix-spec-proposals/pull/4010
Our notification settings are affected by this.

**Comment by Fabian42** [comment]
Can confirm with the "cinny-desktop" AUR package and KDE.

**Comment by ThisNekoGuy** [comment]
On Android I straight up get a PWA crash:

<img width="1080" height="2268" alt="Image" src="https://github.com/user-attachments/assets/ed48210e-1047-4426-bc57-e4ca25515fcf" />

```ts
TypeError: Illegal constructor. Use ServiceWorkerRegistration.showNotification() instead.
    at https://app.cinny.in/assets/index-P5zqKpXs.js:121:25673
    at https://app.cinny.in/assets/index-P5zqKpXs.js:121:25987
    at qv (https://app.cinny.in/assets/index-P5zqKpXs.js:9:24296)
    at vF (https://app.cinny.in/assets/index-P5zqKpXs.js:9:42451)
    at https://app.cinny.in/assets/index-P5zqKpXs.js:9:40763
    at x (https://app.cinny.in/assets/index-P5zqKpXs.js:2:11818)
    at MessagePort.T (https://app.cinny.in/assets/index-P5zqKpXs.js:2:12187)
```

For me, this seems to happen on some room joins; not always, but it's happened to me at least twice
