### ISSUE TITLE
Unable to browse rooms or send messages. 

### ISSUE THREAD

**Issue by OpaqueReptile** [ajbura/cinny#750]
### Describe the bug

Trying to send a message into a room or simply browse rooms results in the following, which causes the app to become unresponsive:

```
main.b8455fa246356d403cf5.bundle.js:2 Uncaught TypeError: Cannot read properties of null (reading 'displayName')
    at main.b8455fa246356d403cf5.bundle.js:2:2929160
    at Is (main.b8455fa246356d403cf5.bundle.js:2:2929221)
    at a.e (main.b8455fa246356d403cf5.bundle.js:2:3948672)
    at i.emit (main.b8455fa246356d403cf5.bundle.js:2:530478)
    at Object.SELECT_ROOM (main.b8455fa246356d403cf5.bundle.js:2:2971217)
    at a.value (main.b8455fa246356d403cf5.bundle.js:2:2973970)
    at t._invokeCallback (main.b8455fa246356d403cf5.bundle.js:2:538321)
    at t.dispatch (main.b8455fa246356d403cf5.bundle.js:2:538143)
    at Bu (main.b8455fa246356d403cf5.bundle.js:2:2965955)
    at onClick (main.b8455fa246356d403cf5.bundle.js:2:3518748)
```

![image](https://user-images.githubusercontent.com/1264375/184430883-8d4c45d8-f4a6-450a-8c4a-64c3196f47c3.png)

### Reproduction

1. Launch App
2. Browse any two rooms
3. Try to send a message

### Expected behavior

Normal chat behavior

### Platform and versions

```shell
OS: Windows 11
Version: Cinny desktop 2.1.2
Homeserver: inferiorlattice.com (Synapse 1.64.0)
```

**Comment by OpaqueReptile** [comment]
Further details, realized I had a personal custom emoji added from FluffyChat that seems to be missing the displayName key - removing that in FluffyChat fixed the issue.

**Comment by kfiven** [comment]
Not a Cinny issue as per #747 ([This](https://github.com/Sorunome/matrix-doc/blob/2e2987b646afcffc92f0a53eb13fad84249200c4/proposals/2545-emotes.md) was the culprit.)
